Upgrade to solidus 3 x
nebulab/solidus_zip_zones pull request #6
Opened 2022-08-23 18:15 UTC by DanielePalombo

2022-10-07 11:01 UTC, elia requested changes
looks good, just noted a typo that might be causing the CI to fail

2022-10-07 11:01 UTC, elia commented on spec/models/solidus_zip_zones/tax_location_decorator_spec.rb
> +  subject(new_tax_location) { Spree::Tax::TaxLocation.new }
missing colon?

2022-10-07 12:30 UTC, cpfergus1 approved these changes
Looks good to me, I added that colon to help push things along!

2022-10-11 14:01 UTC, cpfergus1 commented on spec/models/solidus_zip_zones/tax_location_decorator_spec.rb
> +  subject(new_tax_location) { Spree::Tax::TaxLocation.new }
I got this in 3d1c828

2022-10-11 14:52 UTC, merged